### ISSUE TITLE
Spinner java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by vepak** [rey5137/material#219]
I'm trying to use com.rey.material.widget.Spinner in a fragment but I'm getting the following error when I try to change spinner value. Could you please help me with the issue. Thank you for your time.

Here is the code and error

import android.os.Bundle;
import android.support.v4.app.Fragment;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import android.widget.ArrayAdapter;
import com.rey.material.widget.Spinner;

public class SpinnerFragment extends Fragment {

    View SpinV;

    String items[] = {"Choose type of vehicle","Car","Bus","Two wheeler","Lorry","Other"};
    Spinner spn_label;

    public SpinnerFragment() {
        // Required empty public constructor
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        if(SpinV==null) {
            SpinV = inflater.inflate(R.layout.fragment_spinns, container, false);
        }
        spn_label = (Spinner)SpinV.findViewById(R.id.spinner_label);

        ArrayAdapter<String> adapter = new ArrayAdapter<String>(getActivity(), R.layout.row_spn, items);
        adapter.setDropDownViewResource(R.layout.row_spn_dropdown);
        spn_label.setAdapter(adapter);

        return SpinV;
    }

}

java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
            at android.view.ViewGroup.addViewInner(ViewGroup.java:3881)
            at android.view.ViewGroup.addView(ViewGroup.java:3734)
            at android.view.ViewGroup.addView(ViewGroup.java:3679)
            at android.view.ViewGroup.addView(ViewGroup.java:3655)
            at com.rey.material.widget.Spinner.onDataInvalidated(Spinner.java:927)
            at com.rey.material.widget.Spinner.setSelection(Spinner.java:422)
            at com.rey.material.widget.Spinner.performItemClick(Spinner.java:898)
            at com.rey.material.widget.Spinner$DropdownPopup$3.onItemClick(Spinner.java:1271)
            at com.rey.material.widget.Spinner$DropDownAdapter.onClick(Spinner.java:1140)
            at com.rey.material.widget.RippleManager.run(RippleManager.java:100)
            at com.rey.material.widget.RippleManager.onClick(RippleManager.java:93)
            at android.view.View.performClick(View.java:4759)
            at android.view.View$PerformClick.run(View.java:19770)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5232)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by khangneovip** [comment]
I have same problem

**Comment by aumidbek** [comment]
Same problem

**Comment by shah-nishant** [comment]
Same problem

**Comment by rey5137** [comment]
I have published 1.2.1.6-SNAPSHOT version that fixed this issue. Pls test it out.

**Comment by aumidbek** [comment]
Snapshot version works okay. Thanks a lot.

**Comment by aumidbek** [comment]
@rey5137, When you apply snapshot version changes to normal version?

**Comment by shiran4** [comment]
Using 1.2.2-SNAPSHOT version and this is still happening. I can't use the mentioned version because other things are then not working..
